# Generated by Django 5.0.14 on 2026-02-10 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
            options={
                'db_table': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='principal.equipo')),
            ],
            options={
                'db_table': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ligas',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='principal.liga'),
        ),
        migrations.CreateModel(
            name='MovimientoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga'), ('apuesta', 'Apuesta'), ('premio', 'Premio')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_juego', 'En juego'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_locales', to='principal.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitantes', to='principal.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='principal.liga')),
            ],
            options={
                'db_table': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=50)),
                ('minuto', models.IntegerField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='principal.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='principal.partido')),
            ],
            options={
                'db_table': 'EventosPartidos',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.FloatField()),
                ('empate', models.FloatField()),
                ('visitante', models.FloatField()),
                ('activa', models.BooleanField(default=False)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.partido')),
            ],
            options={
                'db_table': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='pendiente', max_length=10)),
                ('tipo', models.CharField(choices=[('ganador', 'Ganador'), ('overunder', 'Over / Under')], max_length=20)),
                ('seleccion_ganador', models.CharField(blank=True, max_length=20, null=True)),
                ('over_under', models.CharField(blank=True, choices=[('over', 'Más de'), ('under', 'Menos de')], max_length=10, null=True)),
                ('linea_goles', models.FloatField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.partido')),
            ],
            options={
                'db_table': 'Apuestas',
            },
        ),
        migrations.CreateModel(
            name='PartidoHistoricoMLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_local', models.FloatField()),
                ('elo_visitante', models.FloatField()),
                ('diff_elo', models.FloatField()),
                ('partidos_local', models.IntegerField()),
                ('partidos_visitante', models.IntegerField()),
                ('resultado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.liga')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.partido')),
            ],
            options={
                'db_table': 'PartidosHistoricosMLP',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.liga')),
            ],
            options={
                'ordering': ['-puntos', '-goles_favor'],
                'unique_together': {('equipo', 'liga')},
            },
        ),
        migrations.CreateModel(
            name='EloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1200)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.liga')),
            ],
            options={
                'db_table': 'EloEquipos',
                'unique_together': {('equipo', 'liga')},
            },
        ),
    ]
