# Generated by Django 5.0.14 on 2025-06-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
