# Generated by Django 5.0.14 on 2026-02-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
    ]
